language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"
before_script:
  # Start a fake x server so that matplotlib doesn't fail
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - python -m doctest tests/scan_class.txt
cache: pip
